packages:
  - 'packages/*'

catalogs:
  dev:
    '@antfu/eslint-config': ^4.13.1
    '@types/node': ^20.8.10
    '@types/prompts': ^2.4.9
    eslint: ^9.27.0
    eslint-plugin-format: ^1.0.1
    ts-node: ^10.9.1
    tsdown: "^0.12.3"
    typescript: ^5.2.2
  prod:
    cac: ^6.7.14
    chalk: ^5.4.1
    prompts: ^2.4.2


